name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
      - uses: actions/checkout@v2

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npx pnpm i

      - name: Use cached fonts
        uses: actions/cache/restore@v3
        id: cache-fonts
        with:
          path: ~/share/fonts/LXGWWenKai/
          key: font-lxgw-wenkai
          
      - name: Download fonts
        if: steps.cache-font.outputs.cache-hit != 'true'
        uses: robinraju/release-downloader@v1.7
        with:
          repository: lxgw/LxgwWenKai
          tag: v1.250
          fileName: "*.ttf"
          tarBall: false
          zipBall: false
          outfilePath: ~/share/fonts/LXGWWenkai/
      
      - name: Update cache
        if: steps.cache-font.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/share/fonts/LXGWWenKai/
          key: font-lxgw-wenkai
          
      - name: Install fonts
        run: sudo fc-cache -fv

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
